version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          command: |
            ./gradlew clean test

      - deploy:
          name: Publish main to release repository
          command: |
            if [ "$CIRCLE_BRANCH" = "main" ]; then
              ./gradlew publish
            fi
